using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using RequireJsCore.Configuration;
using RequireJsCore.Models;
using System;
using System.Collections.Generic;

namespace RequireJsCore
{
    public class RequireRendererConfiguration
    {
        private string baseUrl = string.Empty;

        private string requireJsUrl = string.Empty;

        private string urlArgs = null;

        private string entryPointRoot = "~/ClientApp/";

        private bool loadOverrides = true;

        private int waitSeconds = 7;

        private IList<string> configPaths = new[] { "~/RequireJS.json" };

        private readonly IUrlHelper _urlHelper;

        public RequireRendererConfiguration(IUrlHelper urlHelper)
        {
            LocaleSelector = helper => System.Threading.Thread.CurrentThread.CurrentUICulture.Name.Split('-')[0];
            ProcessConfig = config => { };
            ProcessOptions = options => { };

            _urlHelper = urlHelper;
        }

        /// <summary>
        /// Scripts base url
        /// </summary>
        public string BaseUrl
        {
            get
            {
                return baseUrl;
            }

            set
            {
                baseUrl = value;
            }
        }

        /// <summary>
        /// RequireJS javascript file url
        /// </summary>
        public string RequireJsUrl
        {
            get
            {
                return this.requireJsUrl;
            }

            set
            {
                this.requireJsUrl = value;
            }
        }

        /// <summary>
        /// Value passed to the urlArgs setting of RequireJS
        /// </summary>
        public string UrlArgs
        {
            get
            {
                return urlArgs;
            }

            set
            {
                urlArgs = value;
            }
        }

        /// <summary>
        /// Value passed to the urlArgs setting of RequireJS
        /// </summary>
        public int WaitSeconds
        {
            get
            {
                return waitSeconds;
            }
            set { waitSeconds = value; }
        }

        /// <summary>
        /// List of RequireJS config file paths
        /// </summary>
        public IList<string> ConfigurationFiles
        {
            get
            {
                return configPaths;
            }

            set
            {
                configPaths = value;
            }
        }

        /// <summary>
        /// Scripts folder relative path (ex. ~/Scripts/)
        /// </summary>
        public string EntryPointRoot
        {
            get
            {
                return entryPointRoot;
            }

            set
            {
                entryPointRoot = value;
            }
        }

        /// <summary>
        /// Logger for library output
        /// </summary>
        public IRequireJsLogger Logger { get; set; }

        /// <summary>
        /// A value indicating whether overrides generated by the AutoCompressor should be loaded.
        /// </summary>
        public bool LoadOverrides
        {
            get
            {
                return loadOverrides;
            }

            set
            {
                loadOverrides = value;
            }
        }

        public ConfigCachingPolicy ConfigCachingPolicy { get; set; }

        public bool CacheConfigObject { get; set; }

        /// <summary>
        /// Gets or sets a function that returns the current locale in short format (ex. "en")
        /// </summary>
        public Func<IHtmlHelper, string> LocaleSelector { get; set; }

        public Action<JsonRequireOutput> ProcessConfig { get; set; }

        public Action<JsonRequireOptions> ProcessOptions { get; set; }

        public string GenerateContentUrl(string url)
        {
            return _urlHelper.Content(url);
        }
    }
}
